# Generated by Django 5.1 on 2024-11-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geomjson', models.CharField(blank=True, max_length=255, null=True)),
                ('statename', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'managed': True,
            },
        ),
    ]
